//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cricketer
    {
        public int CricketerId { get; set; }
        public string CricketerName { get; set; }
        public string CricketerCity { get; set; }
        public string CricketerCountry { get; set; }
        public int CricketerSalary { get; set; }
    }
}
