//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalInfo
    {
        public int PID { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        public int userID { get; set; }
    
        public virtual country country1 { get; set; }
        public virtual state state1 { get; set; }
        public virtual User User { get; set; }
    }
}
